# -*- coding: utf-8 -*-
"""torre_de_hanoi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k--eWZ6b2QUS6A9npfq2QKpuLmCp7QZx
"""

from array import array


# Exceções customizadas exigidas pelo professor
class PilhaCheiaErro(Exception):
    """Exceção gerada quando a pilha está cheia."""
    pass


class PilhaVaziaErro(Exception):
    """Exceção gerada quando a pilha está vazia."""
    pass


class TipoErro(Exception):
    """Exceção gerada quando o tipo do dado é inválido."""
    pass


class Pilha:
    def __init__(self, capacidade, tipo):
        if capacidade <= 0:
            raise ValueError("A capacidade deve ser maior que zero.")

        if tipo not in (int, float, str):
            raise TipoErro("O tipo deve ser int, float ou str.")

        self.capacidade = capacidade
        self.tipo = tipo
        self.quantidade = 0

        # Instanciação da classe array com capacidade estática predefinida
        if tipo is int:
            self.dados = array('q', [0] * capacidade)
        elif tipo is float:
            self.dados = array('d', [0.0] * capacidade)
        else:  # tipo is str (caractere)
            self.dados = array('u', ['\0'] * capacidade)

    def empilha(self, dado):
        if self.pilha_esta_cheia():
            raise PilhaCheiaErro("A pilha está cheia.")

        # Validação estrita de tipo
        if self.tipo is str:
            if not isinstance(dado, str) or len(dado) != 1:
                raise TipoErro("O dado deve ser um único caractere.")
        elif type(dado) is not self.tipo:
            raise TipoErro(f"Tipo inválido. Esperado: {self.tipo.__name__}.")

        # Armazena o dado na posição física do topo e incrementa o ponteiro
        self.dados[self.quantidade] = dado
        self.quantidade += 1

    def desempilha(self):
        if self.pilha_esta_vazia():
            raise PilhaVaziaErro("A pilha está vazia.")

        # Decrementa o ponteiro do topo e retorna o elemento
        self.quantidade -= 1
        dado = self.dados[self.quantidade]
        self.dados[self.quantidade] = 0

        return dado



    def pilha_esta_vazia(self):
        return self.quantidade == 0

    def pilha_esta_cheia(self):
        return self.quantidade == self.capacidade

    def troca(self):
        if self.quantidade < 2:
            raise PilhaVaziaErro("É necessário ter pelo menos dois elementos para trocar.")

        topo = self.quantidade - 1
        abaixo = self.quantidade - 2

        # Troca os elementos do topo e do elemento imediatamente abaixo
        self.dados[topo], self.dados[abaixo] = (
            self.dados[abaixo],
            self.dados[topo]
        )

    def tamanho(self):
        return self.quantidade

def mostra_pinos(pinos, movimentos):

    print(f"\nPosição: {movimentos} movimentos\n")

    for pino in  pinos:
       if len(pino.dados) == 0:
          print('[]')
       else:
          print(f'{pino.dados.tolist()}\n')

def mover_disco(origem, destino):
    disco = origem.desempilha()

    # Verifica se o movimento respeita a regra
    if not destino.pilha_esta_vazia():
        topo = destino.dados[destino.tamanho() - 1]

        if disco > topo:
            # Se o movimento for inválido, devolve o disco
            origem.empilha(disco)
            raise ValueError(
                "Não é permitido colocar um disco maior sobre um menor."
            )

    destino.empilha(disco)

def hanoi(n, origem, destino, intermediario, pinos,
          movimentos, M, estado):
    if n == 0:
        return

    # Move os n-1 discos menores para o pino intermediário
    hanoi(
        n - 1,
        origem,
        intermediario,
        destino,
        pinos,
        movimentos,
        M,
        estado
    )

    # Move o maior disco restante para o destino
    mover_disco(origem, destino)

    estado[0] += 1

    # Mostra a situação a cada M movimentos
    if estado[0] % M == 0:
        mostra_pinos(
            pinos,
            estado[0]
        )

        input("Pressione ENTER para continuar...")

    # Move os n-1 discos do intermediário para o destino
    hanoi(
        n - 1,
        intermediario,
        destino,
        origem,
        pinos,
        movimentos,
        M,
        estado
    )

# ==========================================
# PROGRAMA PRINCIPAL
# ==========================================

print("==========================================")
print("          TORRE DE HANÓI")
print("==========================================")

while True:
    try:
      N = int(input("Digite a quantidade de discos N: "))

      while N <= 0:
        print("N deve ser maior que zero.")
        N = int(input("Digite a quantidade de discos N: "))
      break
    except ValueError:
      print('Entrada inválida. Digite um número inteiro positivo.')


while True:
    try:
      M = int(input("Digite a quantidade de movimentos M entre visualizações: "))

      while M <= 0:
        print("M deve ser maior que zero.")
        M = int(input("Digite a quantidade de movimentos M entre visualizações: "))
      break
    except ValueError:
      print('Entrada inválida. Digite um número inteiro positivo.')



# Criação dos três pinos
pino_inicial        = Pilha(N, int)
pino_intermediario  = Pilha(N, int)
pino_destino        = Pilha(N, int)

pinos = [pino_inicial, pino_destino, pino_intermediario]


# Coloca os discos no pino inicial.
# N é o maior disco e 1 é o menor.
for disco in range(N, 0, -1):
    pino_inicial.empilha(disco)

# Quantidade teórica mínima de movimentos
print(f"\nMovimentos esperados: {2**N - 1}")

# Apresenta a posição inicial
mostra_pinos(
    pinos,
    0
)

input("Pressione ENTER para iniciar a solução...")


# Lista usada para manter o contador entre as chamadas recursivas.
# O valor começa em zero.
estado = [0]


# Resolve a Torre de Hanói
hanoi(
    N,
    pino_inicial,
    pino_destino,
    pino_intermediario,
    pinos,
    0,
    M,
    estado
)


# Caso o número total de movimentos não seja múltiplo de M,
# apresenta também a última posição.
if estado[0] % M != 0:
    mostra_pinos(
        pinos,
        estado[0]
    )


print("==========================================")
print("          SOLUÇÃO FINAL")
print("==========================================")

mostra_pinos(
    pinos,
    estado[0]
)

print(f"Total de movimentos: {estado[0]}")